closeEvent & Restore Function
AlexIII/tcc-g15 pull request #19
Opened 2024-02-04 13:10 UTC by the0cp

1. Update the closeEvent:
- Display a dialog with "Exit" and "Minimize" buttons upon clicking the "X", with "Exit" triggering the `onExit()` function and "Minimize" hiding the window to the system tray.
- Add a checkbox "don't ask me again".
2. Delete(comment) `changeEvent()`.
3. Add function to restore settings.

Here's the demo(mp4): 

https://github.com/AlexIII/tcc-g15/assets/63190431/686bd57e-3d80-4d8a-b6ee-f81406ae4f6b

2024-02-04 13:49 UTC, AlexIII requested changes
Hi! Thank you for the contribution!

Please see the review.

2024-02-04 13:49 UTC, AlexIII commented on src/Backend/__pycache__/AWCCThermal.cpython-312.pyc
Remove all the `__pycache__` files from the commit. Leave only *.py source files.

2024-02-04 13:49 UTC, AlexIII commented on src/GUI/AppGUI.py
> +    exitValue = "app/exit"
Capitalize and rename to `MinimizeOnCloseFlag` (or choose other meaningful name)

2024-02-04 13:49 UTC, AlexIII commented on src/GUI/AppGUI.py
> +        '''
Remove this code if it's not needed.

2024-02-04 13:49 UTC, AlexIII commented on src/GUI/AppGUI.py
> +    '''
Remove this code if it's not needed

2024-02-05 03:21 UTC, the0cp commented
Thank you for your code review. I am new to PyQt. Sorry some details were not handled well. 
As a Dell G series user I'm glad you developed this software as an alternative to the **awful** AWCC

2024-02-06 06:35 UTC, merged

2024-02-06 06:37 UTC, AlexIII commented
Accepted. The changes will be integrated to the master branch upon the next release.
Again, thank you for your contribution to the project!